### ISSUE TITLE
Multiple buttons pressed

### ISSUE THREAD

**Issue by bkopf** [Kudos5/tdt4258#1]
https://github.com/Kudos5/tdt4258/blob/0b8ab0fb567c19967f79d194af04203ccf971e85/exercise-1/ex1-polling.s#L48

Will this handle multiple buttons pressed at once? Or should we "`orr` away" the button bits we're not checking for before the `cmp`?

**Comment by Kudos5** [comment]
Currently the behaviour is as follows:
Multiple buttons pressed simultaneously: Nothing happens. It does not match any of the cases.
Multiple buttons pressed, then all but one are released: Function of the remaining button is triggered once.

In the current implementation, if we were to check each button individually(as you suggest), then the action of each held button will trigger whenever a new button is pressed or released. If this is the desired behaviour then we'll implement it. We haven't yet decided how we want the system to behave so I just implemented something random : P

Let's discuss how we want the system to behave and then implement that : )

**Comment by bkopf** [comment]
Right, just wanted to make sure I understand your code correctly. So far so good!

> if we were to check each button individually(as you suggest), then the action of each held button will trigger whenever a new button is pressed or released

True, we probably don't want that. We can discuss the details in our next meeting. :)
