### ISSUE TITLE
Bit fields in the struct?

### ISSUE THREAD

**Issue by bkopf** [Kudos5/tdt4258#4]
https://github.com/Kudos5/tdt4258/blob/14a7c2b0ac24b1153642b5f95f2805b9bc6400d0/exercise-2/sound.c#L18 Nitpicking: Consider using [bit fields](https://en.wikipedia.org/wiki/Bit_field#C_programming_language) to avoid unnecessary memory usage by the struct. 10 bit frequency example: `unsigned frequency : 10;` 

Although:
- We have to make sure the compiler supports it first.
- We should use the right number of bits to avoid padding. Check the struct size with the `sizeof()` operator.

**Comment by Kudos5** [comment]
To avoid complicating things I would avoid optimisations like this until they are necessary.

They should be supported in any standard-compliant compiler.

It is a good idea though. By enabling struct packing as well can save significant memory this way, given that there are enough of these structs. The trade-off is that more instructions are needed to work with the structs, costing more time and energy. However, using less memory might make us able to save power by disabling some ram blocks.
